[IPPAN-1833] Porting rpcapd to IP Phone

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6258,11 +6258,11 @@ echo "$as_me: Enabling SITA ACN support" >&6;}
 
 else
 
-if test -z "$with_pcap" && test "$cross_compiling" = yes; then
-	{ { echo "$as_me:$LINENO: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&5
-echo "$as_me: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&2;}
-   { (exit 1); exit 1; }; }
-fi
+#if test -z "$with_pcap" && test "$cross_compiling" = yes; then
+#	{ { echo "$as_me:$LINENO: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&5
+#echo "$as_me: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&2;}
+#   { (exit 1); exit 1; }; }
+#fi
 
 # Check whether --with-pcap was given.
 if test "${with_pcap+set}" = set; then
@@ -6594,11 +6594,11 @@ fi
  	fi
 	{ echo "$as_me:$LINENO: result: $ac_cv_linux_vers" >&5
 echo "${ECHO_T}$ac_cv_linux_vers" >&6; }
- 	if test $ac_cv_linux_vers = unknown ; then
- 		{ { echo "$as_me:$LINENO: error: cannot determine linux version when cross-compiling" >&5
-echo "$as_me: error: cannot determine linux version when cross-compiling" >&2;}
-   { (exit 1); exit 1; }; }
- 	fi
+# 	if test $ac_cv_linux_vers = unknown ; then
+# 		{ { echo "$as_me:$LINENO: error: cannot determine linux version when cross-compiling" >&5
+#echo "$as_me: error: cannot determine linux version when cross-compiling" >&2;}
+#   { (exit 1); exit 1; }; }
+# 	fi
 	if test $ac_cv_linux_vers -lt 2 ; then
 		{ { echo "$as_me:$LINENO: error: version 2 or higher required; see the INSTALL doc for more info" >&5
 echo "$as_me: error: version 2 or higher required; see the INSTALL doc for more info" >&2;}
